#!/usr/bin/env bash
#Installs Nginx and configure it

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create a new configuration file for the redirection
cat << EOF > /etc/nginx/conf.d/redirect.conf
server {
    listen 80;
    server_name one-techschool.tech;
    return 301 http://www.github.com\$request_uri;
}
EOF

# Test the configuration file to make sure it's valid
if nginx -t; then
    # If the configuration file is valid, reload Nginx to apply the new configuration
    service nginx reload
fi
